import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Navbar from "@/components/navbar";
import { Toaster } from "@/components/ui/sonner";
//import ErrorBoundary from "@/components/error-boundary";

const dmSans = DM_Sans({
  variable: "--font-sans",
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Apikeys Next JS UI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${dmSans.variable} antialiased`}
      >
{/*         <ErrorBoundary> */}
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Navbar />
            {children}
            <Toaster />
          </ThemeProvider>
{/*         </ErrorBoundary> */}
      </body>
    </html>
  );
}
